name: Generate File Structure

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Aegis repository
      uses: actions/checkout@v3
      with:
        path: aegis

    - name: Checkout Aegis-website repository
      uses: actions/checkout@v3
      with:
        repository: NKPGAMER/Aegis-website
        token: ${{ secrets.PAT_TOKEN }}
        path: aegis-website

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Generate file structure JSON
      run: |
        cd aegis
        echo "const fs = require('fs');
        const path = require('path');

        function getFileStructure(dir, baseDir = '') {
          let result = [];
          const items = fs.readdirSync(dir);

          for (const item of items) {
            const fullPath = path.join(dir, item);
            const relativePath = path.join(baseDir, item);
            const stats = fs.statSync(fullPath);

            if (stats.isDirectory()) {
              result.push({
                type: 'directory',
                name: item,
                path: relativePath,
                children: getFileStructure(fullPath, relativePath)
              });
            } else {
              result.push({
                type: 'file',
                name: item,
                path: relativePath,
                size: stats.size
              });
            }
          }

          return result;
        }

        const structure = getFileStructure('.');
        fs.writeFileSync('../aegis-website/src/project/aegis/structure.json', 
          JSON.stringify(structure, null, 2));" > generate-structure.js

        node generate-structure.js

    - name: Commit and push changes
      run: |
        cd aegis-website
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add src/project/aegis/structure.json
        git commit -m "Update file structure JSON" || echo "No changes to commit"
        git push
